#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

cp system/decomposeParDict.ptscotch system/decomposeParDict
runApplication snappyHexMesh -overwrite

#sed -i 's/symmetryPlane/empty/g' processor*/constant/polyMesh/boundary

runApplication extrudeMesh

runApplication decomposePar -copyZero

find . -type f -iname "*level*" -exec rm {} \;

runParallel renumberMesh -overwrite

runParallel pisoFoam

runApplication reconstructParMesh -constant

runApplication reconstructParunParallel $(getApplication)


#------------------------------------------------------------------------------
